### PR TITLE
`RestoreTo[F[_], G[_]]` extends `Lift[G[_], F[_]]`.

### LINKED ISSUE #117: Function allowing to get back into exceptional context in `RestoreTo`
Wouldn't it be useful to have a function allowing to get back from `G[_]` to `F[_]` in `RestoreTo`?

### PR DESCRIPTION
**Pull request by oskin1**
Close #117

### CODE REVIEW

File: zio/core/src/main/scala/tofu/zioInstances/package.scala [hunk 1]
```diff
@@ -17,7 +17,13 @@ class ZioInstances1 extends ZioInstances2 {
   private[this] val rioTofuInstanceAny: RioTofuInstance[Any] = new RioTofuInstance
   final def rioTofuInstance[R]: RioTofuInstance[R]           = rioTofuInstanceAny.asInstanceOf[RioTofuInstance[R]]
 
-  private[this] val zioErrorsToInstanceAny: ZioTofuErrorsToInstance[Any, Any, Nothing] = new ZioTofuErrorsToInstance
+  private[this] implicit val containsInstanceAny: Contains[Nothing, Any] =
+    new Contains[Nothing, Any] {
+      def set(s: Nothing, b: Any): Nothing = s
+      def extract(s: Nothing): Any = s.asInstanceOf[Any]
```
Comment (road21) [inline zio/core/src/main/scala/tofu/zioInstances/package.scala]: asInstanceOf is redundant
Also, may be this instance should be somewhere in optics module?

Comment (oskin1) [reply zio/core/src/main/scala/tofu/zioInstances/package.scala]: Maybe, but I haven't found more suitable place for such dummy implicit.

Comment (road21) [reply zio/core/src/main/scala/tofu/zioInstances/package.scala]: I think such instance can be abstracted to smth like:
```scala
def subtype[A, B >: A]: Contains[A, B] = PContains[A, B](identity)((x, _) => x)
``` 
and moved to ```tofu.optics.functions```.
@Odomontois, what do you think?

Comment (Odomontois) [reply zio/core/src/main/scala/tofu/zioInstances/package.scala]: I agree with moving, but I like the current non-allocating version more.

Comment (Odomontois) [reply zio/core/src/main/scala/tofu/zioInstances/package.scala]: Also, I believe such instance would break Lens laws in general

File: zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala [hunk 2]
```diff
@@ -78,10 +79,12 @@ object ZioTofuInstance {
   }
 }
 
-class ZioTofuErrorsToInstance[R, E, E1] extends ErrorsTo[ZIO[R, E, *], ZIO[R, E1, *], E] {
+class ZioTofuErrorsToInstance[R, E, E1](implicit lens: Contains[E1, E])
```
Comment (Odomontois) [inline zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala]: It looks we need only `Extract` instance here

File: zio/core/src/main/scala/tofu/zioInstances/package.scala [hunk 3]
```diff
@@ -17,7 +17,13 @@ class ZioInstances1 extends ZioInstances2 {
...
 
-  private[this] val zioErrorsToInstanceAny: ZioTofuErrorsToInstance[Any, Any, Nothing] = new ZioTofuErrorsToInstance
+  private[this] implicit val containsInstanceAny: Contains[Nothing, Any] =
+    new Contains[Nothing, Any] {
+      def set(s: Nothing, b: Any): Nothing = s
+      def extract(s: Nothing): Any = s
+    }
+
+  private[this] def zioErrorsToInstanceAny: ZioTofuErrorsToInstance[Any, Any, Nothing] = new ZioTofuErrorsToInstance[Any, Any, Nothing]
   final def zioTofuErrorsToInstance[R, E, E1]: ZioTofuErrorsToInstance[R, E, E1] =
```
Comment (Odomontois) [inline zio/core/src/main/scala/tofu/zioInstances/package.scala]: This instance is not sound anymore.
You can not transform `ZIO[R, E1, A]` to `ZIO[R, E, A]` without any prior knowledge about how to map `E1` to `E`
I'm afraid trying to cast arbitrary `E1` to `Nothing` would bring `ClassCastException`

Comment (Odomontois) [reply zio/core/src/main/scala/tofu/zioInstances/package.scala]: I suppose best we can do here is a change `E1` to `Nothing` explicitly for that instance.

File: zio/core/src/main/scala/tofu/zioInstances/package.scala (hunk 1 above)
Comment (road21) [reply zio/core/src/main/scala/tofu/zioInstances/package.scala]: Yep, sorry, my mistake.
Counterexample: for `Contains[Boolean, Boolean]` such instance, we have: ```extract(set(true, false)) = true```

File: zio/core/src/main/scala/tofu/zioInstances/package.scala (hunk 3 above)
Comment (oskin1) [reply zio/core/src/main/scala/tofu/zioInstances/package.scala]: @Odomontois, you mean `final def zioTofuErrorsToInstance[R, E]: ZioTofuErrorsToInstance[R, E, Nothing]`?

File: zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala [hunk 4]
```diff
@@ -78,10 +79,12 @@ object ZioTofuInstance {
   }
 }
 
-class ZioTofuErrorsToInstance[R, E, E1] extends ErrorsTo[ZIO[R, E, *], ZIO[R, E1, *], E] {
+class ZioTofuErrorsToInstance[R, E, E1](implicit lens: Extract[E1, E])
```
Comment (Odomontois) [inline zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala]: So now the only use of the `lens` parameter is to `Extract` something from `Nothing`
This is perfectly legit and could not touch performance (since mapError is never applied).
But it looks like we need at least one additional instance , e.g.
```scala
final def zioTofuExtractErrorsInstance[R, E, E1: * Extract E1]: ZioTofuErrorsToInstance[R, E, E1] = 
  new ZioTofuErrorsToInstance
```

To justify this encoding.

File: optics/core/src/main/scala/tofu/optics/functions.scala [hunk 5]
```diff
@@ -56,4 +56,6 @@ object functions {
   def some[A]: Subset[Option[A], A] = Subset[Option[A]](identity)(Some(_))
 
   def none[A]: Subset[Option[A], Unit] = Subset[Option[A]](_ => Some(()))(_ => None)
+
+  def extractAnyFromNothing: Extract[Nothing, Any] = (s: Nothing) => s
```
Comment (Odomontois) [inline optics/core/src/main/scala/tofu/optics/functions.scala]: Well, `Extract[A, B]` unlike `Lens[A, B]` is perfectly legal  for any `A <: B`, so it would be better to see more general case here.
